---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Your names and team name here"
date: "11/16/2021"
output: pdf_document
---
Outline:
# Load Packages


```{r load-packages}
print(2)
```

# Load Data
```{r load-data}
oxford_lockdown<-readr::read_csv(file = '~/R/TBD2/data/OxCGRT_US_latest.csv')
flu<-readr::read_csv(file = '~/R/TBD2/data/State_Custom_Data.csv')
ilinet <- readr::read_csv("~/R/TBD2/data/ILINet.csv")
```

```{r daily_change_to_weekly}
ox2 <- oxford_lockdown %>%
  filter(!is.na(StringencyIndex) & !is.na(RegionName) & !(RegionName=="")) %>%
  transform(Date = as.Date(as.character(Date), "%Y%m%d")) %>%
  mutate(Year = format(Date, "%Y"))%>%
  mutate(Week = strftime(Date, format= "%V"))%>%
  group_by(CountryName, CountryCode, RegionName, RegionCode, Year, Week) %>%
  summarize(Stringency_Index = mean(StringencyIndex))
```

```{r}
flu2<-flu%>%
  mutate(Year = ifelse(WEEK>=40 & WEEK<=53, substr(SEASON,3,4),substr(SEASON,6,7)))%>%
  mutate(Year = paste("20",Year,sep=""))
```


```{r change data format}
ox2$Week<-as.numeric(ox2$Week)
ox2$Year<-as.numeric(ox2$Year)
flu2$WEEK<- as.numeric(flu2$WEEK)
flu2$Year<- as.numeric(flu2$Year)
ilinet$YEAR<-as.numeric(ilinet$YEAR)
ilinet$WEEK<- as.numeric(ilinet$WEEK)
```


```{r merge flu& ili report data}
flu_ili <- left_join(flu2,ilinet,by=c("SUB AREA" ="REGION","WEEK","Year"="YEAR"))
flu_ili<-flu_ili%>% rename("YEAR" = "Year","STATE" ="SUB AREA")
```

```{r merge flu_ili with ox2}
 ox2<-ox2%>%
   rename("STATE" = "RegionName","YEAR"= "Year","WEEK" = "Week")
 merged <-left_join(ox2, flu_ili,by = c("STATE","WEEK","YEAR"))
```

```{r}
merged2<-merged%>%
  select("YEAR","WEEK","Stringency_Index", 'NUM INFLUENZA DEATHS','NUM PNEUMONIA DEATHS',
         'NUM COVID-19 DEATHS','TOTAL DEATHS','%UNWEIGHTED ILI')
merged2<- subset(merged2, select = -c(CountryName,CountryCode,RegionCode ))
merged2
```
```{r}
merged2 %>%
  filter(YEAR == 2020 & !is.na(`NUM COVID-19 DEATHS`)) %>%
  #mutate(covid_deaths = log( `NUM COVID-19 DEATHS`)) %>%
  group_by(WEEK) %>%
  summarise (mean_stringency_index = mean(Stringency_Index) ,mean_covid_death = mean(`NUM COVID-19 DEATHS`))%>%
  ggplot(aes(x= mean_stringency_index, y = mean_covid_death)) +
  geom_point()
```
```{r}
merged2 %>%
  filter(YEAR == 2020 & !is.na(`NUM INFLUENZA DEATHS`)) %>%
  #mutate(covid_deaths = log( `NUM COVID-19 DEATHS`)) %>%
  group_by(WEEK) %>%
  summarise (mean_stringency_index = mean(Stringency_Index), mean_influenza_death = mean(`NUM INFLUENZA DEATHS`)) %>%
  ggplot(aes(x= mean_stringency_index, y = mean_influenza_death)) +
  geom_point()
```
```{r}
merged2 %>%
  filter(YEAR == 2020 & !is.na(`NUM PNEUMONIA DEATHS`)) %>%
  #mutate(covid_deaths = log( `NUM COVID-19 DEATHS`)) %>%
  group_by(WEEK) %>%
  summarise (mean_stringency_index = mean(Stringency_Index), mean_pneumonia_death = mean(`NUM PNEUMONIA DEATHS`)) %>%
  ggplot(aes(x= mean_stringency_index, y = mean_pneumonia_death)) +
  geom_point()
```
```{r}

```

```{r}
merged2%>%
  ggplot(aes(x="WEEK", y = "TOTAL DEATHS"))+
  geom_point()
```