---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Your names and team name here"
date: "11/16/2021"
output: pdf_document
---
Outline:

#Introduction

Starting in 2020, public health measures against the spread of respiratory disease were taken in an effort to slow or prevent the spread of COVID-19. These measures were much more significant than in previous years, as the primary strategies against the spread of respiratory disease in the United States are typically vaccination and encouraging frequent hand-washing, but measures against COVID-19 included shutting down large parts of society and moving online, as well as enforcement or encouragement of face coverings and vaccinations when available. This report studies how these public health measures may have affected the spread of other infectious disease by focusing on influenza hospitalizations and deaths in the United States, as the flu is one of the most common and deadly diseases each year in the U.S., and shares many characteristics with COVID-19.

#Flu seasons during the COVID-19 Pandemic vs. past flu seasons

Have flu deaths and hospitalizations changed during the COVID-19 pandemic compared to past years? If so, is this difference statistically significant?
```{r seasons compare}
#data/libraries
library(dplyr)
library(tidyverse)
library(viridis)
fludata <-read.csv("~/R/TBD2/data/ILINet.csv", header=TRUE)
#line graph
aggfludata <- fludata %>%
  filter(REGION != 'Commonwealth of the Northern Mariana Islands') %>%
  transform(year = as.character(YEAR), week = as.character(WEEK), total_flu = as.numeric(ILITOTAL)) %>%
  mutate(yearweek = ifelse(WEEK <= 9,paste(year, week, sep = '0'),paste(year, week, sep = ''))) %>%
  group_by(yearweek) %>%
  drop_na() %>%
  summarize(total_flu_patients = sum(total_flu)) %>%
  ggplot(aes(x = yearweek, y = total_flu_patients)) +
  geom_line()
```
#table
fludata %>%
  
#insert model?
```
Based on the data, the effects of the flu for each season were lower 
    
#Comparison of lockdowns and flu levels by state/comparison of flu levels by lockdown stringency (?)
compare states/lockdown and mask levels (stringency index) to flu hospitalizations or deaths
  consider using a model
    test which model fits best
    test for and explain statistical significance
talk about why flu levels may be lower
  more protective measures against respiratory illnesses
  possibly more issues going to hospital for flu/collecting data
  is the population most affected by flu being reduced by COVID?